# Default values for restapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# set restpi image
image:
  registry: docker.io
  repository: xiliangma/restapi
  tag: 4
  pullPolicy: IfNotPresent

# add service
service:
  type: NodePort
  ports:
  - devName: dev
    devPort: 18080
    devTargetPort: 18080
  - prodName: prod
    prodPort: 18088
    prodTargetPort: 18088
  - httpsName: https
    httpsPort: 1443
    httpsTargetPort: 1443

#  add externalDatabase when mariadb.enabled is set to false
externalDatabase:
  host: localhost
  user: root
  password: ""
  database: uranus_local
  port: 3306

mariadb:
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false
  db:
    name: uranus_local
    user: root
    password: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
     cpu: 300m
     memory: 512Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
